//! Manages the on-disk layout of bare repositories: a flat namespace of
//! `<root>/<name>.git` directories (no users/orgs, since nugitea has none),
//! mirroring the bare-repo shape Gitea itself creates via `git init --bare`.

use std::path::{Path, PathBuf};

use anyhow::{bail, Context, Result};

use crate::gitcmd;

/// Resolves repo names to on-disk paths under a root directory.
pub struct Store {
    pub root: PathBuf,
}

/// Validates that name is safe to use as a repo name: the only defense
/// against path traversal, since there is no auth layer to rely on.
fn validate_name(name: &str) -> Result<()> {
    let mut chars = name.chars();
    match chars.next() {
        Some(c) if c.is_ascii_alphanumeric() || c == '_' => {}
        _ => bail!("invalid repo name {name:?}"),
    }
    if !name
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || matches!(c, '_' | '-' | '.'))
    {
        bail!("invalid repo name {name:?}");
    }
    Ok(())
}

impl Store {
    /// Returns a Store rooted at root, creating the directory if needed.
    pub fn new(root: impl AsRef<Path>) -> Result<Self> {
        let root = root.as_ref();
        std::fs::create_dir_all(root).with_context(|| format!("create repo root {root:?}"))?;
        let root = root
            .canonicalize()
            .with_context(|| format!("resolve repo root {root:?}"))?;
        Ok(Store { root })
    }

    /// Returns the absolute path to the bare repo directory for name
    /// (without requiring it to exist).
    pub fn path(&self, name: &str) -> Result<PathBuf> {
        validate_name(name)?;
        Ok(self.root.join(format!("{name}.git")))
    }

    /// Reports whether the named repo exists on disk.
    pub async fn exists(&self, name: &str) -> bool {
        match self.path(name) {
            Ok(path) => tokio::fs::try_exists(&path).await.unwrap_or(false),
            Err(_) => false,
        }
    }

    /// Resolves a wire-form repo reference — an HTTP path segment
    /// ("demo.git") or an SSH command path ("/demo.git") — to a validated
    /// repo name and its on-disk path, or None if the name is invalid or
    /// the repo doesn't exist. The one place both transports go to turn
    /// untrusted client input into a safe name, instead of each
    /// reimplementing the strip-and-validate steps themselves.
    pub async fn resolve(&self, raw: &str) -> Option<(String, PathBuf)> {
        let raw = raw.strip_prefix('/').unwrap_or(raw);
        let name = raw.strip_suffix(".git")?;
        let path = self.path(name).ok()?;
        if tokio::fs::try_exists(&path).await.unwrap_or(false) {
            Some((name.to_string(), path))
        } else {
            None
        }
    }

    /// Returns the names of all repos under the root.
    pub fn list(&self) -> Result<Vec<String>> {
        let mut names = Vec::new();
        for entry in std::fs::read_dir(&self.root)? {
            let entry = entry?;
            if entry.file_type()?.is_dir() {
                if let Some(name) = entry.file_name().to_str().and_then(|s| s.strip_suffix(".git")) {
                    names.push(name.to_string());
                }
            }
        }
        Ok(names)
    }

    /// Creates a new bare repository named `name` (git init --bare, then
    /// hook installation), mirroring Gitea's
    /// git.InitRepository + gitrepo.CreateDelegateHooks flow.
    pub async fn init_bare(&self, name: &str) -> Result<PathBuf> {
        let path = self.path(name)?;
        if path.exists() {
            bail!("repo {name:?} already exists");
        }
        tokio::fs::create_dir_all(&path).await?;

        gitcmd::run(&path, &["init", "--bare", "."]).await?;

        let nugitea_bin =
            std::env::current_exe().context("resolve nugitea binary path")?;
        install_hooks(&path, &nugitea_bin).await?;

        Ok(path)
    }
}

/// hook_names are the git server-side hooks nugitea installs a delegator
/// for. Each delegator just execs `nugitea hook <name>` and passes stdin
/// through, mirroring Gitea's hooks/<name> -> hooks/<name>.d/gitea
/// delegation (see modules/gitrepo/hooks.go) but flattened to a single
/// script since nugitea has no per-hook custom-script fan-out to support.
const HOOK_NAMES: [&str; 3] = ["pre-receive", "update", "post-receive"];

async fn install_hooks(repo_path: &Path, nugitea_bin: &Path) -> Result<()> {
    let hooks_dir = repo_path.join("hooks");
    tokio::fs::create_dir_all(&hooks_dir).await?;

    let bin_quoted = shell_quote_single(&nugitea_bin.to_string_lossy());
    for name in HOOK_NAMES {
        let script = format!(
            "#!/bin/sh\n# AUTO GENERATED BY NUGITEA, DO NOT MODIFY\nexec {bin_quoted} hook {name} \"$@\"\n"
        );
        let path = hooks_dir.join(name);
        tokio::fs::write(&path, script)
            .await
            .with_context(|| format!("write hook {name}"))?;

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            tokio::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o755)).await?;
        }
    }
    Ok(())
}

/// POSIX single-quote escaping, safe for embedding an arbitrary path into a
/// generated shell script.
fn shell_quote_single(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}
